name: CI/CD for Blood Pressure Bot

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t blood_pressure_bot .

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Add Railway CLI to PATH
        run: echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          SVC_ID: my-service-id
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        steps:
          - uses: actions/checkout@v3
          - run: railway up --service=${{ env.SVC_ID }}

